### ISSUE TITLE
Kill hanging Tendermint process on Windows

### ISSUE THREAD

**Issue by iasonrovis** [valory-xyz/olas-operate-app#346]
Tendermint processes are sometimes left hanging when Pearl is closed by users on Windows. This causes conflicts when reloading Pearl and attempting to deploy services locally.

Originated from:
User cannot start the agent after updating to the latest release version rc127.

[pearl_logs_2024-09-11-0.1.0-rc127.zip](https://github.com/user-attachments/files/16976488/pearl_logs_2024-09-11-0.1.0-rc127.zip)

[Discord ticket](https://discord.com/channels/899649805582737479/1281194141870460970/1283640691569983509)

**Comment by truemiller** [comment]
Looks related the hanging tendermint processes sometimes experienced on Windows.

```
2024-09-11T19:14:28.056Z cli: [2024-09-11 21:14:28,053][ERROR] Error 13
Traceback (most recent call last):
  File "operate\cli.py", line 246, in _call
    return await f(request)
  File "operate\cli.py", line 545, in _create_services
    await run_in_executor(_fn)
  File "operate\cli.py", line 167, in run_in_executor
    res = await future
  File "concurrent\futures\thread.py", line 58, in run
  File "operate\cli.py", line 543, in _fn
    manager.deploy_service_locally(hash=service.hash)
  File "operate\services\manage.py", line 1366, in deploy_service_locally
    deployment.build(force=force)
  File "operate\services\service.py", line 600, in build
    return self._build_host(force=force, chain_id=chain_id)
  File "operate\services\service.py", line 507, in _build_host
    shutil.rmtree(build)
  File "shutil.py", line 750, in rmtree
  File "shutil.py", line 615, in _rmtree_unsafe
  File "shutil.py", line 615, in _rmtree_unsafe
  File "shutil.py", line 615, in _rmtree_unsafe
  File "shutil.py", line 620, in _rmtree_unsafe
  File "shutil.py", line 618, in _rmtree_unsafe
```

Temporary fix for now is to: 
1. Exit Pearl
2. Open Task Manager
3. Kill `tendermint` processes they are still running
4. Restart Pearl

@iasonrovis, @solarw recommended this fix [in Slack](https://valory-workspace.slack.com/archives/C07CKA5TN5V/p1725967145603209), it is agent related.
